// dashboard/agenda2/examples/frameworks/angular/filtering/src/app/app.component.ts
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { BryntumCalendarComponent } from '@bryntum/calendar-angular';
import { Calendar, EventModel, EventStore } from '@bryntum/calendar/calendar.lite.umd.js';
import { calendarConfig } from './app.config';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html'
})
export class AppComponent implements AfterViewInit {
    @ViewChild(BryntumCalendarComponent) calendarComponent: BryntumCalendarComponent;

    private calendar: Calendar;
    private eventStore: EventStore;

    // calendar configuration
    calendarConfig = calendarConfig;

    filterTriggers = {
        filter : {
            align : 'start',
            cls   : 'b-fa b-fa-filter'
        }
    };

    highlightTriggers = {
        filter : {
            align : 'start',
            cls   : 'b-fa b-fa-highlighter'
        }
    };

    /**
     * Find by name text field change handler
     */
    onFindChange({ value }: any): void {
        // We filter using a RegExp, so quote significant characters
        const val = value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

        // A filter with an id replaces any previous filter with that id.
        // Leave any other filters which may be in use in place.
        this.calendar.eventStore.filter({
            id       : 'eventNameFilter',
            filterBy : (event: EventModel) => event.name.match(new RegExp(val, 'i'))
        });
    }

    /**
     * Highlight text field change handler
     */
    onHighlightChange({ value }: any): void {
        const
            val = value.toLowerCase(),
            { eventStore, calendar } = this;

        // Calendars refresh on any data change so suspend that.
        // We will trigger the store's change event when we're done.
        eventStore.suspendEvents();

        // Loop through all events in the store
        eventStore.forEach((task) => {
            // The cls field is a DomClassList with add and remove methods
            if (val !== '' && task.name.toLowerCase().includes(val)) {
                task.cls.add('b-match');
            }
            else {
                task.cls.remove('b-match');
            }
        });
        eventStore.resumeEvents();

        // Announce that data has changed which will refresh UIs.
        eventStore.trigger('change');

        calendar.element.classList[value.length > 0 ? 'add' : 'remove']('b-highlighting');
    }

    /**
     * Called after View is initialized
     */
    ngAfterViewInit(): void {
        this.calendar = this.calendarComponent.instance;
        this.eventStore = this.calendar.eventStore;

        // Uncomment the code below in this method to start "logging" eventStore events
        // const eventStore = this.calendar.calendarInstance.eventStore;
        // eventStore.on('change', ({ action, record, records }) => {
        //
        //     const eventNames = records && records.map(eventRecord => eventRecord.name).join(',');
        //
        //     switch (action) {
        //         case 'update':
        //             console.log(`Event updated: ${record.name}`);
        //             break;
        //
        //         case 'add':
        //             console.log(`Events added: ${eventNames}`);
        //             break;
        //
        //         case 'remove':
        //             console.log(`Events removed: ${eventNames}`);
        //             break;
        //     }
        // });
    }

    onCalendarEvents(event: any): void {
        // Uncomment the code in this method to start "logging" events
        // switch (event.type) {
        //     case 'aftereventsave':
        //         console.log(`New event saved: ${event.eventRecord.name}`);
        //         break;
        //
        //     case 'beforeeventdelete':
        //         console.log(`Events removed: ${event.eventRecords.map(eventRecord => eventRecord.name).join(',')}`);
        //         break;
        // }
    }
}

<bryntum-demo-header
    link = "../../../../../#example-frameworks-angular-filtering"
></bryntum-demo-header>

<div class = "demo-toolbar align-right">
    <bryntum-text-field
        label = "Filter tasks by name"
        clearable = true
        keyStrokeChangeDelay = 100
        [triggers] = "filterTriggers"
        (onChange) = "onFindChange($event)"
    ></bryntum-text-field>
    <bryntum-text-field
        label = "Highlight tasks"
        clearable = true
        keyStrokeChangeDelay = 100
        [triggers] = "highlightTriggers"
        (onChange) = "onHighlightChange($event)"
    ></bryntum-text-field>
</div>

<bryntum-calendar
    [crudManager] = "calendarConfig.crudManager"
    [eventEditFeature] = "calendarConfig.features.eventEdit"
    [date] = "calendarConfig.date"
    [modes] = "calendarConfig.modes"
    (onCatchAll) = "onCalendarEvents($event)"
></bryntum-calendar>

// dashboard/agenda2/examples/frameworks/react/javascript/filtering/src/App.js
/**
 * Application
 */
import React, { Fragment, useRef } from 'react';

import {
    BryntumCalendar,
    BryntumDemoHeader,
    BryntumThemeCombo,
    BryntumTextField
} from '@bryntum/calendar-react';
import { calendarConfig, filterConfig, highlightConfig } from './AppConfig';
import './App.scss';

const App = () => {
    const calendarRef = useRef(null);

    const filterChangeHandler = ({ value }) => {
        // We filter using a RegExp, so quote significant characters
        value = value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

        // A filter with an id replaces any previous filter with that id.
        // Leave any other filters which may be in use in place.
        calendarRef.current.instance.eventStore.filter({
            id: 'eventNameFilter',
            filterBy: event => event.name.match(new RegExp(value, 'i'))
        });
    };
    const highlightChangeHandler = ({ value }) => {
        value = value.toLowerCase();
        const { instance } = calendarRef.current;
        const { eventStore } = instance;

        // Calendars refresh on any data change so suspend that.
        // We will trigger the store's change event when we're done.
        eventStore.suspendEvents();

        // Loop through all events in the store
        eventStore.forEach(task => {
            // The cls field is a DomClassList with add and remove methods
            if (value !== '' && task.name.toLowerCase().includes(value)) {
                task.cls.add('b-match');
            } else {
                task.cls.remove('b-match');
            }
        });

        eventStore.resumeEvents();

        // Announce that data has changed which will refresh UIs.
        eventStore.trigger('change');

        instance.element.classList[value.length > 0 ? 'add' : 'remove']('b-highlighting');
    };

    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-filtering"
                children={<BryntumThemeCombo />}
            />
            <div className="demo-toolbar align-right">
                <BryntumTextField onChange={filterChangeHandler} {...filterConfig} />
                <BryntumTextField onChange={highlightChangeHandler} {...highlightConfig} />
            </div>
            <BryntumCalendar ref={calendarRef} {...calendarConfig}></BryntumCalendar>
        </Fragment>
    );
};

export default App;
